stages:
  - Release
  - Deploy

# based on: https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml
release-image:
  stage: Release
  image: docker:20.10.7
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHA"

deploy-ecs:      
  stage: Deploy  
  when: manual
  image: 'registry.gitlab.com/gitlab-org/cloud-deploy/aws-ecs:latest'
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  script:
    - ecs update-task-definition
